### ISSUE TITLE
About Support for Python？

### ISSUE THREAD

**Issue by imperio-wxm** [RedisLabs/spark-redis#25] opened 2016-04-13 16:00 UTC
Hi, I use spark with python, but I noticed java python and R API bindings are not provided.
Any plans to include python API?

**Comment by sunheehnus** [comment] 2016-04-13 23:37
Hi @imperio-wxm , it is in plan, I will ping you when it is ready

**Comment by imperio-wxm** [comment] 2016-04-14 01:57
@sunheehnus thank you!

**Comment by hampsterx** [comment] 2016-05-26 02:18
this would be epic for python :)

**Comment by senseysensor** [comment] 2017-02-09 14:20
@sunheehnus any estimations about time? Really no way for now to use with python?

**Comment by dvirsky** [comment] 2017-02-09 14:26
@senseysensor python support is currently not on the roadmap for the coming months. if more users will ask for this, it might change of course.

**Comment by senseysensor** [comment] 2017-02-09 15:01
Well, will hope this will be implemented.

Can I ask you here one more thing. I'm new in spark (just doing experiments to find out if it is suitable for our needs – data analysis). We plan to use python.
So, would be this equivalent – use this connector or, on other hand, manually from code connect to redis, load data to dataframe and than analyze it?

**Comment by dvirsky** [comment] 2017-02-09 15:25
The connector is mainly "spark sugar" that converts streams redis objects to RDDs for convenience. You can simply connect to redis if all you need is to read some keys. 
It does have the advantage of trying to align a redis cluster to a spark cluster in a way that most redis accesses will be to local nodes, if each machine is running both redis and spark.

but if all you need is to access some data in a redis server, just use the default redis client and you'll be fine.

**Comment by nguyenign** [comment] 2018-03-12 14:24
+1 for python!

**Comment by wu1boy** [comment] 2018-04-27 07:14
hello. Any update on this? @sunheehnus @dvirsky .

**Comment by wu1boy** [comment] 2018-04-27 07:16
How do you currently connect to redis?

**Comment by slhttc123** [comment] 2018-05-10 02:53
+1 for python. Python has a large community. It is imperative to support Python.

**Comment by q475254344** [comment] 2018-08-02 03:56
+1 for python.

**Comment by gkorland** [comment] 2018-08-15 19:41
We are planing to add Python support in the next release

**Comment by sumanentc** [comment] 2018-09-06 17:12
Any plans to include JAVA API?

**Comment by buxizhizhoum** [comment] 2018-09-14 02:14
+1 for python.

**Comment by DerryChan** [comment] 2018-09-27 13:30
@gkorland Hello, will spark-redis has any plan including Java API?

**Comment by fe2s** [comment] 2018-09-28 12:18
@DerryChan, @sumanentc 
There is no specific Java API, but you can still use the library with Java because of Scala/Java Interoperability.

RDD methods like `toRedisKV`, `fromRedisKV`, etc are in `RedisContext` class. 
Because of the way Scala compiled into Java, some methods may look ugly in Java, for example `redisContext.fromRedisHash$default$2()`. We will need to create a clean Java API to address that.

 Here is an example of using Redis RDD in Java:

```java
 SparkConf sparkConf = new SparkConf().setAppName("MyApp").setMaster("local[*]")
                .set("redis.host", "localhost")
                .set("redis.port", "6379");

        RedisConfig redisConfig = new RedisConfig(new RedisEndpoint(sparkConf));

        JavaSparkContext jsc = new JavaSparkContext(sparkConf);

        RedisContext redisContext = new RedisContext(jsc.sc());
        List<Tuple2<String, String>> list = new ArrayList<Tuple2<String, String>>();
        list.add(new Tuple2<String, String>("a", "1"));
        list.add(new Tuple2<String, String>("b", "2"));
        list.add(new Tuple2<String, String>("c", "3"));

        JavaRDD<Tuple2<String, String>> rdd = jsc.parallelize(list);
        int ttl = 0;

        redisContext.toRedisKV(rdd.rdd(), ttl, redisConfig);
```

Another example of Spark Streaming app:
```java
 SparkConf sparkConf = new SparkConf().setAppName("MyApp").setMaster("local[2]")
                .set("spark.streaming.stopGracefullyOnShutdown", "true")
                .set("redis.host", "localhost")
                .set("redis.port", "6379");


        JavaStreamingContext jssc = new JavaStreamingContext(sparkConf, Durations.milliseconds(1000));

        RedisConfig redisConfig = new RedisConfig(new RedisEndpoint(sparkConf));

        RedisStreamingContext redisStreamingContext = new RedisStreamingContext(jssc.ssc());
        String[] keys = new String[]{"myList"};
        RedisInputDStream<Tuple2<String, String>> redisStream =
                redisStreamingContext.createRedisStream(keys, StorageLevel.MEMORY_ONLY(), redisConfig);

        redisStream.print();

        jssc.start();
        jssc.awaitTermination();
```

**Comment by sbsar6** [comment] 2018-10-16 10:56
+1 for python! When is the next release with it due out please?

**Comment by lisawhite137** [comment] 2018-10-17 10:50
+1 for python

**Comment by fe2s** [comment] 2018-10-17 11:27
@sbsar6 , @lisawhite137 
Could you please also vote for the specific features you are looking with Python? It will help us to prioritize the backlog.

**Comment by sbsar6** [comment] 2018-10-17 12:36
Specifically I would really love to be able to write directly from a pyspark dataframe to a Redis db rather than having to collect the info to a python object which is a bad idea memory wise, thanks

**Comment by fe2s** [comment] 2018-10-17 13:40
@sbsar6 , writing DataFrames with Python is actually already available in this branch 
https://github.com/RedisLabs/spark-redis/tree/dataframe

The scala documentation is here https://github.com/RedisLabs/spark-redis/blob/dataframe/doc/dataframe.md

I will add a Python documentation soon, but for now here is a quick guide:
1. Checkout and build `dataframe` branch with `mvn clean package -DskipTests`
2. `./bin/pyspark --jars /your/path/to/spark-redis-2.3.1-SNAPSHOT-jar-with-dependencies.jar`
```python
df = spark.read.json("examples/src/main/resources/people.json")
df.write.format("org.apache.spark.sql.redis").option("table", "people").option("key.column", "name").save()
loadedDf = spark.read.format("org.apache.spark.sql.redis").option("table", "people").load()
loadedDf.show()
```
3. Check the data with redis-cli:
```
127.0.0.1:6379> hgetall people:Justin
1) "age"
2) "19"
3) "name"
4) "Justin"
```

Please let us know if it fully addresses your use case.

**Comment by sbsar6** [comment] 2018-10-17 14:19
@fe2s  Thanks that just made my day

**Comment by sbsar6** [comment] 2018-10-25 10:15
@fe2s hi, so I have set it up to run via the command line jar, but I am now trying to run it in a python file. I added the config to spark session : 
spark = SparkSession.builder.appName("Spark Data").getOrCreate()
    spark.conf.set("spark.redis.host", "....") etc
but running it I get a Failed to find data source: org.apache.spark.sql.redis. error. any ideas? Thanks

**Comment by sbsar6** [comment] 2018-10-25 10:30
> There are also some answers that might help you like https://stackoverflow.com/questions/27698111/how-to-add-third-party-java-jars-for-use-in-pyspark

Great thanks will give them a try

**Comment by sbsar6** [comment] 2018-10-25 12:28
I tried setting the config to use the Jar and it seemed to load OK, but then had the same error that it couldn't find it trying to write to Redis: spark.conf.set("spark.jars", "/opt/sp-spark/jars/spark-redis-1.4.1.jar"). I tried submitting to cluster too, but then my logging doesn't work so can't debug why nothing happened, but it didn't seem to connect to redis at all that way although job completed. I pointed it to use Spark for logging but cluster isn't accessible when it is finished to check the logs there.

**Comment by fe2s** [comment] 2018-10-25 12:34
`/opt/sp-spark/jars/spark-redis-1.4.1.jar` - this is an old version, you should use the latest version from master branch

**Comment by sbsar6** [comment] 2018-10-29 10:46
Thanks for all the help so far, upgraded to 2.3 now and can find OK by the looks but getting: error occurred while calling o291.save. : redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
I can connect to the DB fine with the same credentials though and monitoring the connections no attempt seems to be made from pyspark to get refused. Any ideas on what I am missing? Thanks

**Comment by fe2s** [comment] 2018-10-29 10:53
Hi @sbsar6 ,
Is it pyspark shell or script?
How do you configure connection to Redis?

**Comment by sbsar6** [comment] 2018-10-29 11:07
A script, connection is configured:
spark = SparkSession.builder.appName("Spark_Processor").getOrCreate()
    spark.conf.set("spark.redis.host", "***")
    spark.conf.set("spark.redis.port", "6379")
    spark.conf.set("spark.redis.auth", "***")
    spark.conf.set("spark.jars", "/opt/sp-spark/jars/spark-redis-2.3.1-M1.jar")

**Comment by sbsar6** [comment] 2018-10-29 13:36
I get the same just trying to write a file from the pyspark shell too just as an FYI

**Comment by sbsar6** [comment] 2018-10-29 13:54
Same trying to do it in Scala too, so is something set up wrong do you reckon?

**Comment by fe2s** [comment] 2018-10-29 14:16
I guess you are configuring context in a wring way, can you try the following please?

```python
SparkSession 
    .builder 
    .appName("Spark_Processor") 
    .config("spark.redis.host", "***") 
    .config("spark.redis.port", "6379") 
    .config("spark.redis.auth", "***") 
    .config("spark.jars", "/opt/sp-spark/jars/spark-redis-2.3.1-M1.jar") 
    .getOrCreate()
```

**Comment by sbsar6** [comment] 2018-10-29 14:31
You are a legend and I will name my next hamster after you! Why the other way didn't work I don't know though, have altered variables that way before.

**Comment by sbsar6** [comment] 2018-10-30 11:38
One final question haha, the data is writing to Redis now but I am getting an error:
 error occurred while calling o158.save. : java.lang.IllegalStateException: SaveMode is set to ErrorIfExists and dataframe already exists in Redis and contains data.
Is there a way to change SaveMode to overwrite do you know?

**Comment by fe2s** [comment] 2018-10-30 11:44
It should be something like this I think

```python
df.write.format("org.apache.spark.sql.redis")
   .option("table", "people")
   .option("key.column", "name")
   .mode("overwrite")
   .save()
```

Please see https://spark.apache.org/docs/2.3.0/api/python/_modules/pyspark/sql/readwriter.html for details

**Comment by justinrmiller** [comment] 2019-04-15 02:07
@fe2s Can this ticket be closed out?

**Comment by fe2s** [comment] 2019-04-15 02:12
@justinrmiller -  I think so. Closing.

**Closed by fe2s** 2019-04-15 02:12 UTC

**Comment by kars45** [comment] 2019-11-03 06:38
Is there support for structured streaming in python?

**Comment by fe2s** [comment] 2019-11-03 16:59
@kars45, yes

**Comment by y-tee** [comment] 2019-12-09 07:54
Hi, I need some help here writing and reading from redis stream with pyspark structured streaming.
I gt the following error when trying to save or read in pyspark shell:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o186.save.
: java.lang.ClassNotFoundException: Failed to find data source: org.apache.spark.sql.redis. Please find packages at http://spark.apache.org/third-party-projects.html
```
1. I tried to pyspark shell --jars location of spark-redis-2.4.0.jar downloaded from [maven](https://mvnrepository.com/artifact/com.redislabs/spark-redis/2.4.0)
2. ```spark=SparkSession.builder.appName("myApp").config("spark.redis.host","127.0.0.1").config("spark.redis.port", "6379").config("spark.jars", "location to same jar").getOrCreate()```
3. ```df=spark.sql("select from hive table")```
4. ```df.write.format("org.apache.spark.sql.redis").option("table", "test").option("key.column", "name").save()```

Any idea what i did wrong here?

**Comment by fe2s** [comment] 2019-12-09 09:28
Hi @y-tee ,
Jedis is missing on your classpath. You have to build and use the jar with dependencies, please take a look here how to build it https://github.com/RedisLabs/spark-redis/blob/master/doc/getting-started.md#build-form-source
Then use --jar option like you did.

**Comment by y-tee** [comment] 2019-12-09 11:04
OMG, Thank you so much! It worked! I used the ```spark-redis-2.4.1-SNAPSHOT-jar-with-dependencies.jar```

**Comment by y-tee** [comment] 2019-12-09 14:14
Hi @fe2s Sorry to interrupt again, i have problem writing out a df as spark streaming in redis stream. 
This is a test and i will just read from redis stream and output to redis stream. Please do let me know if you see any errors. I am not very sure how to implement the foreachbatch function in spark.
1. Read from a redis streams
```sensors = spark.readStream.format("redis").option("stream.keys", "input").schema(types.StructType([types.StructField("sensor-id", types.StringType()),types.StructField("temperature", types.FloatType())])).load()```

2. Define foreachbatch function
```
def foreach_batch_function(df):
    return df.select("sensor-id")
```

3. Start structured streaming again
```query=sensors.writeStream.foreachBatch(foreach_batch_function(sensors)).start()```

I gt the following errors, Does it mean that Dataframe is not supported?what other alternatives do i have?

``````
19/12/09 22:09:34 ERROR MicroBatchExecution: Query [id = 1d8f82e4-c6af-42b5-ad21-8f140055260d, runId = 66e31fc4-c71c-4809-9052-dc4437ae754c] terminated with error
py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File "/usr/lib/spark-current/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 2381, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
  File "/usr/lib/spark-current/python/pyspark/sql/utils.py", line 191, in call
    raise e
  File "/usr/lib/spark-current/python/pyspark/sql/utils.py", line 188, in call
    self.func(DataFrame(jdf, self.sql_ctx), batch_id)
TypeError: 'DataFrame' object is not callable

	at py4j.Protocol.getReturnValue(Protocol.java:473)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:108)
	at com.sun.proxy.$Proxy22.call(Unknown Source)
	at org.apache.spark.sql.execution.streaming.sources.PythonForeachBatchHelper$$anonfun$callForeachBatch$1.apply(ForeachBatchSink.scala:55)
	at org.apache.spark.sql.execution.streaming.sources.PythonForeachBatchHelper$$anonfun$callForeachBatch$1.apply(ForeachBatchSink.scala:55)
	at org.apache.spark.sql.execution.streaming.sources.ForeachBatchSink.addBatch(ForeachBatchSink.scala:35)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:538)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:79)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:144)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:74)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:536)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:62)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:535)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:199)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:167)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:167)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:62)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:167)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:161)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:289)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:200)

``````

**Comment by fe2s** [comment] 2019-12-09 15:40
Only reading Redis stream is supported by the library, writing to Redis stream is not supported. If it's an option, you can read Redis stream, run the computation and write result back to Redis as hashes. Please see a scala example how to do that with `foreachBatch()` function https://github.com/RedisLabs/spark-redis/blob/master/doc/structured-streaming.md#output-to-redis You should be able to do similar with Python.

**Comment by y-tee** [comment] 2019-12-09 16:21
The implementation of foreachbatch function was wrong. It should be done this way:
```
def foreach_batch_function(batch_df,epoch_id):
  batch_df.write.format("org.apache.spark.sql.redis").option("table", "try").option("key.column", "sensor-id").save()
  pass

query=sensors.writeStream.foreachBatch(foreach_batch_function).start()
query.awaitTermination()
```
This will output the batch_df into redis hash batch by batch

**Comment by Matesanz** [comment] 2021-09-30 05:13
For those that want to **install Redis Connector using the url**:

```
from pyspark.sql import SparkSession

group = "com.redislabs"
name = "spark-redis"
scala_version = "2.12"
version = "2.6.0"

redis_spark_pkg = f"{group}:{name}_{scala_version}:{version}" :point_left: 

spark = SparkSession \
    .builder \
    .appName("myApp") \
    .config("spark.redis.host", "localhost") \
    .config("spark.redis.port", "6379") \
    .config("spark.jars.packages", redis_spark_pkg) \
    .getOrCreate()
```
:warning: In redis-spark version <= 2.4.1 [there is no `scala_version`](https://mvnrepository.com/artifact/com.redislabs/spark-redis/2.4.1) so `redis_spark_pkg` would be:
```
redis_spark_pkg = f"{group}:{name}:{version}"
```
:warning: Also check that:
- **Your scala version matches the one required by the package**:
- **Your spark version [matches the one required by the package](https://github.com/RedisLabs/spark-redis#version-compatibility-and-branching)**:
```
$ scala -version
$ spark-submit --version
```

:bulb:  **For more versions [check maven repository](https://mvnrepository.com/artifact/com.redislabs/spark-redis_2.12/2.6.0)**

![image](https://user-images.githubusercontent.com/44867923/135391088-3f98a69d-635f-49e5-ae16-b1b3abcfb4d9.png)
